import { readFile, readdir, stat } from "node:fs/promises";
import path from "node:path";
import { isProjectRelativePath, joinPortablePath, nowIsoDateTime, toPortablePath } from "@unofficial-codex-wiki/core";
import type { AgentDocsManifest } from "@unofficial-codex-wiki/storage";
import { summarizeValidationIssues, type ValidationIssueSummary, type ValidationReport } from "@unofficial-codex-wiki/validator";
import type { PipelineContext } from "../pipeline-context.js";
import { emitProgress } from "../progress.js";
import { writeZipArchive, type ZipArchiveEntry } from "../archive/zip-writer.js";
import { runValidateStep } from "./validate.step.js";

export type ExportCourseMaterialsInput = {
  name?: string;
  output?: string;
};

export type ExportCourseMaterialsResult = {
  generatedAt: string;
  name: string;
  outputPath: string;
  absoluteOutputPath: string;
  byteCount: number;
  entryCount: number;
  pageCount: number;
  chunkCount: number;
  validation: Pick<ValidationReport, "ok" | "errorCount" | "warningCount">;
  instructionPaths: string[];
  materialRoots: string[];
};

export type GeneratedOutputFileHealth = {
  path: string;
  status: "ok" | "empty" | "missing";
  byteCount: number;
};

export type GeneratedMarkdownHealth = {
  manifestAvailable: boolean;
  checkedFileCount: number;
  emptyFileCount: number;
  missingFileCount: number;
  exampleEmptyPaths: string[];
  exampleMissingPaths: string[];
};

export type ExportCourseMaterialsHealthSummary = {
  requiredFiles: GeneratedOutputFileHealth[];
  generatedMarkdown: GeneratedMarkdownHealth;
};

export class ExportCourseMaterialsValidationError extends Error {
  readonly report: ValidationReport;
  readonly health: ExportCourseMaterialsHealthSummary;

  constructor(report: ValidationReport, health: ExportCourseMaterialsHealthSummary) {
    super(`Validation failed with ${report.errorCount} error(s). Run pnpm docs:sync, then rerun pnpm docs:export-course-materials.`);
    this.name = "ExportCourseMaterialsValidationError";
    this.report = report;
    this.health = health;
  }
}

type CourseMaterialsExportManifest = {
  recordType: "course-materials-export";
  generatedAt: string;
  name: string;
  purpose: string;
  notice: string;
  source: {
    agentManifestPath: string;
    pageCount: number;
    chunkCount: number;
  };
  instructions: string[];
  includedRoots: string[];
  includedSupportFiles: string[];
  excludedByDefault: string[];
};

const defaultExportName = "Codex Course Materials";
const instructionPaths = ["README.md", "AGENT_COURSE_CREATION_PROMPT.md", "COURSE_MATERIALS_MANIFEST.json"];
const materialRoots = ["generated/markdown/codex", "generated/agent"];
const supportFiles = ["data/latest/manifest.json", "data/latest/validation-report.json"];
const privateMirrorNotice = [
  "This is an unofficial private local mirror of selected OpenAI Codex documentation.",
  "It is not affiliated with, endorsed by, or maintained by OpenAI.",
  "It is intended for local/internal reading and AI-agent context ingestion only.",
  "Do not publish copied OpenAI documentation generated by this project as a public website."
].join(" ");

export async function runExportCourseMaterialsStep(
  context: PipelineContext,
  input: ExportCourseMaterialsInput = {}
): Promise<ExportCourseMaterialsResult> {
  const generatedAt = nowIsoDateTime();
  const name = normalizeExportName(input.name);
  const outputPath = resolveOutputPath(context, input.output, name, generatedAt);

  emitProgress(context, {
    step: "export",
    phase: "start",
    message: "Validating local mirror before exporting course materials"
  });

  const validation = (await runValidateStep(context)).report;
  if (!validation.ok) {
    const health = await inspectGeneratedOutputHealth(context);
    emitProgress(context, {
      step: "export",
      phase: "failed",
      message: `Validation failed with ${validation.errorCount} error(s)`,
      counts: {
        errors: validation.errorCount,
        warnings: validation.warningCount
      },
      outputPaths: ["data/latest/validation-report.json"]
    });
    throw new ExportCourseMaterialsValidationError(validation, health);
  }

  const agentManifest = await context.storage.readAgentDocsManifest();
  const entries = await buildCourseMaterialsEntries(context, {
    generatedAt,
    name,
    agentManifest
  });

  const absoluteOutputPath = context.storage.toAbsolutePath(outputPath);
  const byteCount = await writeZipArchive(absoluteOutputPath, entries);

  emitProgress(context, {
    step: "export",
    phase: "complete",
    message: `Exported ${entries.length} course material file(s)`,
    counts: {
      pages: agentManifest.pageCount,
      chunks: agentManifest.chunkCount,
      files: entries.length
    },
    outputPaths: [outputPath]
  });

  return {
    generatedAt,
    name,
    outputPath,
    absoluteOutputPath,
    byteCount,
    entryCount: entries.length,
    pageCount: agentManifest.pageCount,
    chunkCount: agentManifest.chunkCount,
    validation: {
      ok: validation.ok,
      errorCount: validation.errorCount,
      warningCount: validation.warningCount
    },
    instructionPaths,
    materialRoots
  };
}

export async function inspectGeneratedOutputHealth(context: PipelineContext): Promise<ExportCourseMaterialsHealthSummary> {
  const requiredFilePaths = [
    "generated/agent/docs.pages.jsonl",
    "generated/agent/docs.chunks.jsonl",
    "generated/search/docs.sqlite"
  ];
  const requiredFiles: GeneratedOutputFileHealth[] = [];

  for (const filePath of requiredFilePaths) {
    requiredFiles.push(await inspectGeneratedOutputFile(context, filePath));
  }

  return {
    requiredFiles,
    generatedMarkdown: await inspectGeneratedMarkdownHealth(context)
  };
}

export function formatExportCourseMaterialsValidationFailure(
  report: ValidationReport,
  health: ExportCourseMaterialsHealthSummary
): string[] {
  const lines = [
    `export-course-materials failed: generated mirror validation failed with ${report.errorCount} error(s) and ${report.warningCount} warning(s).`,
    "The course materials ZIP was not created because the local generated mirror is incomplete or corrupt.",
    "",
    "Generated output health:"
  ];

  for (const file of health.requiredFiles) {
    lines.push(`  - ${file.path}: ${formatGeneratedOutputFileHealth(file)}`);
  }

  const markdown = health.generatedMarkdown;
  if (markdown.manifestAvailable) {
    lines.push(`  - generated Markdown files checked from manifest: ${markdown.checkedFileCount}`);
    lines.push(`  - empty generated Markdown files: ${markdown.emptyFileCount}`);
    lines.push(`  - missing generated Markdown files: ${markdown.missingFileCount}`);
    for (const examplePath of markdown.exampleEmptyPaths.slice(0, 3)) {
      lines.push(`    empty example: ${examplePath}`);
    }
    for (const examplePath of markdown.exampleMissingPaths.slice(0, 3)) {
      lines.push(`    missing example: ${examplePath}`);
    }
  } else {
    lines.push("  - data/latest/manifest.json: missing, so generated Markdown files could not be counted");
  }

  lines.push("", "Top validation issues:");
  for (const summary of summarizeValidationIssues(report, 8)) {
    lines.push(formatValidationIssueSummary(summary));
    if (summary.exampleMessages[0] !== undefined) {
      lines.push(`    ${summary.exampleMessages[0]}`);
    }
  }

  lines.push(
    "",
    "Next commands:",
    "  pnpm docs:sync",
    "  pnpm docs:export-course-materials"
  );

  return lines;
}

function formatValidationIssueSummary(summary: ValidationIssueSummary): string {
  const examplePath = summary.examplePaths[0] === undefined ? "" : `; example: ${summary.examplePaths[0]}`;
  return `  - ${summary.code}: ${summary.count} ${summary.severity}(s)${examplePath}`;
}

function formatGeneratedOutputFileHealth(file: GeneratedOutputFileHealth): string {
  if (file.status === "missing") {
    return "missing";
  }
  if (file.status === "empty") {
    return "empty (0 bytes)";
  }
  return `ok (${file.byteCount} bytes)`;
}

async function inspectGeneratedOutputFile(context: PipelineContext, filePath: string): Promise<GeneratedOutputFileHealth> {
  try {
    const fileStat = await stat(context.storage.toAbsolutePath(filePath));
    const byteCount = fileStat.isFile() ? fileStat.size : 0;
    return {
      path: filePath,
      status: byteCount === 0 ? "empty" : "ok",
      byteCount
    };
  } catch {
    return {
      path: filePath,
      status: "missing",
      byteCount: 0
    };
  }
}

async function inspectGeneratedMarkdownHealth(context: PipelineContext): Promise<GeneratedMarkdownHealth> {
  if (!await context.storage.latestManifestExists()) {
    return {
      manifestAvailable: false,
      checkedFileCount: 0,
      emptyFileCount: 0,
      missingFileCount: 0,
      exampleEmptyPaths: [],
      exampleMissingPaths: []
    };
  }

  const manifest = await context.storage.readLatestManifest();
  const health: GeneratedMarkdownHealth = {
    manifestAvailable: true,
    checkedFileCount: 0,
    emptyFileCount: 0,
    missingFileCount: 0,
    exampleEmptyPaths: [],
    exampleMissingPaths: []
  };

  for (const page of manifest.pages) {
    if (page.status === "failed" || page.status === "removed") {
      continue;
    }

    health.checkedFileCount += 1;
    try {
      const fileStat = await stat(context.storage.toAbsolutePath(page.localMarkdownPath));
      if (fileStat.size === 0) {
        health.emptyFileCount += 1;
        if (health.exampleEmptyPaths.length < 3) {
          health.exampleEmptyPaths.push(page.localMarkdownPath);
        }
      }
    } catch {
      health.missingFileCount += 1;
      if (health.exampleMissingPaths.length < 3) {
        health.exampleMissingPaths.push(page.localMarkdownPath);
      }
    }
  }

  return health;
}

async function buildCourseMaterialsEntries(
  context: PipelineContext,
  metadata: {
    generatedAt: string;
    name: string;
    agentManifest: AgentDocsManifest;
  }
): Promise<ZipArchiveEntry[]> {
  const filePaths = [
    ...await collectProjectRelativeFiles(context, materialRoots),
    ...await collectExistingProjectRelativeFiles(context, supportFiles)
  ];
  const exportManifest = createExportManifest(metadata);
  const entries: ZipArchiveEntry[] = [
    {
      path: "README.md",
      content: createBundleReadme(metadata, exportManifest)
    },
    {
      path: "AGENT_COURSE_CREATION_PROMPT.md",
      content: createAgentCourseCreationPrompt(metadata)
    },
    {
      path: "COURSE_MATERIALS_MANIFEST.json",
      content: `${JSON.stringify(exportManifest, null, 2)}\n`
    }
  ];

  for (const filePath of filePaths) {
    entries.push({
      path: filePath,
      content: await readFile(context.storage.toAbsolutePath(filePath))
    });
  }

  return entries;
}

async function collectProjectRelativeFiles(context: PipelineContext, roots: readonly string[]): Promise<string[]> {
  const filePaths: string[] = [];
  for (const root of roots) {
    filePaths.push(...await collectFilesUnderRoot(context, root));
  }
  return filePaths.sort();
}

async function collectFilesUnderRoot(context: PipelineContext, root: string): Promise<string[]> {
  const rootPath = context.storage.toAbsolutePath(root);
  const entries = await readdir(rootPath, { withFileTypes: true });
  const filePaths: string[] = [];

  for (const entry of entries) {
    const entryPath = joinPortablePath(root, entry.name);
    if (entry.isDirectory()) {
      filePaths.push(...await collectFilesUnderRoot(context, entryPath));
      continue;
    }

    if (entry.isFile()) {
      filePaths.push(entryPath);
    }
  }

  return filePaths;
}

async function collectExistingProjectRelativeFiles(context: PipelineContext, filePaths: readonly string[]): Promise<string[]> {
  const existingPaths: string[] = [];
  for (const filePath of filePaths) {
    try {
      const fileStat = await stat(context.storage.toAbsolutePath(filePath));
      if (fileStat.isFile()) {
        existingPaths.push(filePath);
      }
    } catch {
      // Support files are helpful context, but validation decides whether primary material exists.
    }
  }
  return existingPaths;
}

function createExportManifest(metadata: {
  generatedAt: string;
  name: string;
  agentManifest: AgentDocsManifest;
}): CourseMaterialsExportManifest {
  return {
    recordType: "course-materials-export",
    generatedAt: metadata.generatedAt,
    name: metadata.name,
    purpose: "Private AI-agent handoff bundle for creating a course that teaches the user how to use Codex well.",
    notice: privateMirrorNotice,
    source: {
      agentManifestPath: "generated/agent/docs.manifest.json",
      pageCount: metadata.agentManifest.pageCount,
      chunkCount: metadata.agentManifest.chunkCount
    },
    instructions: [
      "Read README.md first.",
      "Use AGENT_COURSE_CREATION_PROMPT.md as the course-building prompt.",
      "Use generated/agent/docs.chunks.jsonl for retrieval-style planning.",
      "Use generated/markdown/codex/ for full-page source reading."
    ],
    includedRoots: materialRoots,
    includedSupportFiles: supportFiles,
    excludedByDefault: [
      "generated/search/docs.sqlite",
      "data/latest/raw-markdown/",
      "data/latest/raw-html/",
      "data/snapshots/"
    ]
  };
}

function createBundleReadme(
  metadata: {
    generatedAt: string;
    name: string;
    agentManifest: AgentDocsManifest;
  },
  exportManifest: CourseMaterialsExportManifest
): string {
  return [
    `# ${metadata.name}`,
    "",
    privateMirrorNotice,
    "",
    "## What This Bundle Is",
    "",
    "This ZIP contains local Codex documentation materials packaged for a private AI agent that will design a course for the user.",
    "It does not contain generated summaries, AI rewrites, embeddings, a vector database, a chatbot, or a public website.",
    "",
    "## Start Here",
    "",
    "1. Read `AGENT_COURSE_CREATION_PROMPT.md`.",
    "2. Inspect `COURSE_MATERIALS_MANIFEST.json`.",
    "3. Use `generated/agent/docs.manifest.json` to understand the page list.",
    "4. Use `generated/agent/docs.chunks.jsonl` for structured retrieval.",
    "5. Use `generated/markdown/codex/` when you need full-page context.",
    "",
    "## Included Material",
    "",
    `- Pages: ${metadata.agentManifest.pageCount}`,
    `- Chunks: ${metadata.agentManifest.chunkCount}`,
    `- Generated at: ${metadata.generatedAt}`,
    "",
    "Included roots:",
    ...exportManifest.includedRoots.map((root) => `- \`${root}/\``),
    "",
    "Support files:",
    ...exportManifest.includedSupportFiles.map((filePath) => `- \`${filePath}\``),
    "",
    "## Privacy Boundary",
    "",
    "Use these files only for local/internal learning and private AI-agent context ingestion.",
    "Do not publish the copied documentation or this bundle as a public website."
  ].join("\n");
}

function createAgentCourseCreationPrompt(metadata: {
  generatedAt: string;
  name: string;
  agentManifest: AgentDocsManifest;
}): string {
  return [
    "# Agent Course Creation Prompt",
    "",
    "You are an expert technical course designer helping the user learn how to use Codex well.",
    "",
    "Use the bundled files as source material. Treat them as an unofficial private local mirror of Codex documentation, not as official documentation.",
    "",
    "## Your Inputs",
    "",
    "- `generated/agent/docs.manifest.json`: page list, titles, source URLs, local Markdown paths, and chunk IDs.",
    "- `generated/agent/docs.pages.jsonl`: full page records with source metadata.",
    "- `generated/agent/docs.chunks.jsonl`: heading-aware chunks for retrieval and lesson planning.",
    "- `generated/markdown/codex/`: full generated Markdown pages for deeper reading.",
    "- `data/latest/validation-report.json`: validation status for the local mirror.",
    "",
    "## Course Goal",
    "",
    "Create a practical course that teaches the user how to use Codex effectively for real coding work, repo exploration, safe edits, validation, GitHub workflows, plugins, skills, subagents, memories, prompting, and common use cases.",
    "",
    "## How To Work",
    "",
    "1. Start from `generated/agent/docs.manifest.json` to map the source material.",
    "2. Build a course outline from the docs, then refine it around the user's skill level and goals.",
    "3. Prefer practical modules with exercises, commands, checklists, and examples.",
    "4. Use the `use-cases` pages as applied lessons and project ideas.",
    "5. Include safety and verification habits: approvals, sandboxing, validation commands, and careful handling of secrets.",
    "6. Cite or reference source page titles and canonical URLs when making factual claims.",
    "7. Do not invent Codex features that are not supported by the source material.",
    "8. Do not summarize every page mechanically. Turn the source material into a teachable sequence.",
    "",
    "## Suggested Course Shape",
    "",
    "- Module 1: What Codex is good for and how to think with it.",
    "- Module 2: Setup, CLI, IDE, configuration, and safe approvals.",
    "- Module 3: Prompting Codex for repo-grounded coding work.",
    "- Module 4: Reading, editing, testing, and validating changes.",
    "- Module 5: GitHub, CI, code review, and non-interactive workflows.",
    "- Module 6: Skills, plugins, MCP, memories, and subagents.",
    "- Module 7: Applied use cases and project practice.",
    "- Module 8: Advanced habits for reliable long-running work.",
    "",
    "## Output The User Wants",
    "",
    "Produce a course plan with lessons, exercises, practice prompts, expected outcomes, and a recommended learning order.",
    "When the user asks, turn individual modules into detailed lesson content.",
    "",
    "## Bundle Metadata",
    "",
    `- Bundle name: ${metadata.name}`,
    `- Generated at: ${metadata.generatedAt}`,
    `- Page count: ${metadata.agentManifest.pageCount}`,
    `- Chunk count: ${metadata.agentManifest.chunkCount}`
  ].join("\n");
}

function resolveOutputPath(context: PipelineContext, output: string | undefined, name: string, generatedAt: string): string {
  const requestedOutput = output === undefined || output.trim().length === 0
    ? defaultOutputPath(name, generatedAt)
    : ensureZipExtension(toPortablePath(output.trim()));

  const absoluteOutputPath = path.isAbsolute(requestedOutput)
    ? requestedOutput
    : context.storage.toAbsolutePath(requestedOutput);
  const projectRelativePath = context.storage.toProjectRelativePath(absoluteOutputPath);

  if (!isProjectRelativePath(projectRelativePath)) {
    throw new Error("Course materials export output must be inside the project root.");
  }

  return projectRelativePath;
}

function defaultOutputPath(name: string, generatedAt: string): string {
  return joinPortablePath(
    "generated",
    "exports",
    `${toFileSlug(name)}__ai-course-builder__private-local-mirror__${toTimestampSlug(generatedAt)}.zip`
  );
}

function normalizeExportName(name: string | undefined): string {
  const normalizedName = name?.trim();
  return normalizedName === undefined || normalizedName.length === 0 ? defaultExportName : normalizedName;
}

function ensureZipExtension(filePath: string): string {
  return filePath.toLowerCase().endsWith(".zip") ? filePath : `${filePath}.zip`;
}

function toFileSlug(value: string): string {
  const slug = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/gu, "-")
    .replace(/^-+|-+$/gu, "");
  return slug.length === 0 ? "codex-course-materials" : slug;
}

function toTimestampSlug(value: string): string {
  return value
    .replace(/[-:]/gu, "")
    .replace(/\.\d{3}Z$/u, "Z");
}
