export type SupportedEnvName =
  | "CODEX_KB_CACHE_MODE"
  | "CODEX_KB_CRAWLER_PROFILE"
  | "CODEX_KB_MAX_ASSET_CONCURRENCY"
  | "CODEX_KB_MAX_PAGE_CONCURRENCY"
  | "CODEX_KB_PAGE_DELAY_MS"
  | "CODEX_KB_ASSET_DELAY_MS"
  | "CODEX_KB_MAX_REQUESTS_PER_MINUTE"
  | "CODEX_KB_MAX_TOTAL_REQUESTS_PER_RUN"
  | "CODEX_KB_MAX_RETRIES"
  | "CODEX_KB_REQUEST_TIMEOUT_MS";

export const supportedEnvNames = [
  "CODEX_KB_CACHE_MODE",
  "CODEX_KB_CRAWLER_PROFILE",
  "CODEX_KB_MAX_ASSET_CONCURRENCY",
  "CODEX_KB_MAX_PAGE_CONCURRENCY",
  "CODEX_KB_PAGE_DELAY_MS",
  "CODEX_KB_ASSET_DELAY_MS",
  "CODEX_KB_MAX_REQUESTS_PER_MINUTE",
  "CODEX_KB_MAX_TOTAL_REQUESTS_PER_RUN",
  "CODEX_KB_MAX_RETRIES",
  "CODEX_KB_REQUEST_TIMEOUT_MS"
] as const satisfies readonly SupportedEnvName[];
